### ISSUE TITLE
Upgrade step problem with empty string?

### ISSUE THREAD

**Issue by agitator** [eea/eea.facetednavigation#126]
Got this error while upgrading from Plone 4.3.x to 5.1.x

```
Traceback (most recent call last):
  File "/Users/peter/workspace/s2017/eggs/eea.facetednavigation-10.1-py2.7.egg/eea/facetednavigation/criteria/handler.py", line 191, in upgrade
    value = schema[key].fromUnicode(value)
  File "/Users/peter/workspace/s2017/eggs/zope.schema-4.4.2-py2.7.egg/zope/schema/_bootstrapfields.py", line 439, in fromUnicode
    v = int(str)
ValueError: invalid literal for int() with base 10: ''
[1] > /Users/peter/workspace/s2017/eggs/zope.schema-4.4.2-py2.7.egg/zope/schema/_bootstrapfields.py(439)fromUnicode()
-> v = int(str)
(Pdb++) 
(Pdb++) 
(Pdb++) ll
 429         def fromUnicode(self, str):                                                                                                                             
 430             """                                                                                                                                                 
 431             >>> f = Int()                                                                                                                                       
 432             >>> f.fromUnicode("125")                                                                                                                            
 433             125                                                                                                                                                 
 434             >>> f.fromUnicode("125.6") #doctest: +IGNORE_EXCEPTION_DETAIL                                                                                       
 435             Traceback (most recent call last):                                                                                                                  
 436             ...                                                                                                                                                 
 437             ValueError: invalid literal for int(): 125.6                                                                                                        
 438             """                                                                                                                                                 
 439  ->         v = int(str)                                                                                                                                        
 440             self.validate(v)                                                                                                                                    
 441             return v                                                                                                                                            
['self', 'str']
(Pdb++) str
u''

```

bt
```
[0]   /Users/peter/workspace/s2017/eggs/eea.facetednavigation-10.1-py2.7.egg/eea/facetednavigation/criteria/handler.py(191)upgrade()
-> value = schema[key].fromUnicode(value)
```

**Comment by avoinea** [comment]
It fails and raise? Because I see a `try...except...` at line `191`:

```
                try:
                    value = schema[key].fromUnicode(value)
                except ValueError, err:
                    logger.exception(err)
```

**Comment by agitator** [comment]
ah... maybe it was just Products.PDBDebugMode complaining ;-)

**Comment by avoinea** [comment]
@agitator Can be. Can you please confirm and close issue if this is the case?

**Comment by agitator** [comment]
will reopen if it happens again
