### ISSUE TITLE
Pages not loading in Plone 5.1

### ISSUE THREAD

**Issue by ksuess** [eea/eea.facetednavigation#132]
collective.js.jqueryui seems to cause the problem. The pages are not loading in browser. Deactivating Javascript helps, but hm its without Javascript.

_2017-09-20 10:19:27 ERROR ZServerPublisher exception caught
Traceback (most recent call last):
  File "/Applications/Plone_buildout.coredev/plone5devel/eggs/Zope2-2.13.26-py2.7.egg/ZServer/PubCore/ZServerPublisher.py", line 31, in __init__
    response=b)
  File "/Applications/Plone_buildout.coredev/plone5devel/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/Publish.py", line 455, in publish_module
    environ, debug, request, response)
  File "/Applications/Plone_buildout.coredev/plone5devel/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/Publish.py", line 267, in publish_module_standard
    outputBody()
  File "/Applications/Plone_buildout.coredev/plone5devel/eggs/Zope2-2.13.26-py2.7.egg/ZServer/HTTPResponse.py", line 248, in outputBody
    self.stdout.write(str(self))
  File "/Applications/Plone_buildout.coredev/plone5devel/eggs/Zope2-2.13.26-py2.7.egg/ZServer/HTTPResponse.py", line 143, in __str__
    return "\r\n".join(chunks)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 152774: ordinal not in range(128)_

I saved a page with wget and found this:
`<script type="text/javascript" src="http://127.0.0.1:8080/Plone/collective.js.jqueryui.custom.min.js?version=None" data-bundle="jqueryui"></script>`

What can I do to fix this?

**Comment by avoinea** [comment]
@ksuess Sorry for the late reply. I don't know how did I miss this. Is this still an issue?

**Comment by l34marr** [comment]
Hi @ksuess , backup first, then you might try 1) Go ZMI /portal_setup 2) Select Import Tab 3) Select by Title 4) Apply all profiles

Good luck

![eea-import](https://user-images.githubusercontent.com/56113/48247311-d3085500-e42d-11e8-984a-077b1497b31c.png)
